repositories:
  test:
    type: "archive"
    folder:  "/var/www/data/test"
    files: true
  phpunit:
     type: mysqlschemaless
     host:       anycontent-client-phpunit-mysql
     dbname:     phpunit
     user:       root
     password:   root
     cmdl:       "/var/www/tests/resources/repository/cmdl"
http_cache: true
path: "/1"