repositories:
  test:
    type: "archive"
    folder:  "/application/data/test"
    files: true
  phpunit:
     type: mysqlschemaless
     host:       anycontent-client-phpunit-mysql
     dbname:     phpunit
     user:       root
     password:   root
     cmdl:       "/application/tests/resources/repository/cmdl"
     filemanager:
       type: directory
       path: /application/tmp/test/repository/files
       files_url: http://assets.company.com

http_cache: true
anycontent_client_cache: true

path: "/1"