repositories:
  test:
    type: "archive"
    folder:  "/var/www/github/anycontent-repository-service-php/data/test"
    files: true
  test2:
    type: "restlike"
    url:  "http://acrs.github.dev/1/mephisto/info"



