version: '3.5'
services:
  anycontent-repository-service-php72:
    container_name: anycontent-repository-service-php72
    build:
      context: ./build/php
      dockerfile: Dockerfile
    image: anycontent-repository-service-php72:1.0.0
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ../../:/application
    networks:
      - anycontent
networks:
  anycontent:
    driver: "bridge"
    name: "anycontent"